version: "3"
services:
  nginx-react:
    container_name: react-calendar
    image: 0crash0/test:naukograd_calendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production